]0;firejail /usr/bin/meld ./src/main/java/com/bro/dao/UserDAO_LOCAL_4100.java ./src/main/java/com/bro/dao/UserDAO_BASE_4100.java ./src/main/java/com/bro/dao/UserDAO_REMOTE_4100.java Parent pid 4219, child pid 4221

Parent is shutting down, bye...
