]0;firejail /usr/bin/meld ./src/main/java/com/bro/entity/Brotherhood_LOCAL_7053.java ./src/main/java/com/bro/entity/Brotherhood_BASE_7053.java ./src/main/java/com/bro/entity/Brotherhood_REMOTE_7053.java Parent pid 7172, child pid 7174

Parent is shutting down, bye...
